# These substitutions allow the end user to override certain values
substitutions:
  # Device Names
  name: "localbytes-plug-pm"
  friendly_name: "Localbytes Plug PM"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: localbytes.plug-pm
    version: "1.6.0"

esp8266:
  board: esp01_1m

api:

ota:
  - platform: esphome

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://LocalBytes/esphome-localbytes-plug/localbytes-plug-pm.yaml@main

wifi:
  ap:
    ssid: "${friendly_name}"

captive_portal:
